name: Build site
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install pre-reqs
      run: |
        sudo apt-get install -y exiftool libfuse2
        mkdir "$HOME/bin"
        wget -q 'https://imagemagick.org/archive/binaries/magick' -O "$HOME/bin/magick"
        chmod +x "$HOME/bin/magick"
    - name: Build site
      run: |
        export PATH="$HOME/bin:$PATH"
        ./build.ps1
    - name: Validate HTML
      run: |
        wget https://github.com/validator/validator/releases/download/20.6.30/vnu.linux.zip -O vnu.linux.zip
        unzip vnu.linux.zip
        vnu-runtime-image/bin/vnu --skip-non-html public
