name: Build site
on:
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache image files
      uses: actions/cache@v2
      with:
        path: public/img
        key: ${{ runner.os }}-images-${{ hashFiles('src/**/*.png', 'src/**/*.jpe?g', 'src/**/*.gif', 'src/**/*.svg') }}
        restore-keys: ${{ runner.os }}-images-

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - run: npm install 
    - run: npm run-script build
      env:
        CI: true
