name: Build site
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build site
      run: ./build.ps1
    - name: Validate HTML
      run: |
        wget https://github.com/validator/validator/releases/download/20.6.30/vnu.linux.zip -O vnu.linux.zip
        unzip vnu.linux.zip
        vnu-runtime-image/bin/vnu --skip-non-html public
